services:
  dungeon_server:
    build: .
    image: dungeon_explorer:latest
    container_name: dungeon_server
    ports:
      - "8080:8080"       
    stdin_open: true    
    tty: true               
  dungeon_client:
    image: dungeon_explorer:latest   
    build: .
    depends_on:
      - dungeon_server
    environment:

      DUNGEON_SERVER: dungeon_server
    stdin_open: true
    tty: true
    command: ["./client/client_app"]

